# Generated by Django 6.0 on 2026-07-06 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد تخفیف')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='معتبر تا')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف (تومان)'),
        ),
    ]
