# Generated by Django 6.0 on 2026-07-06 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_coupon_order_coupon_code_order_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id'], 'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ تخفیف (تومان)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت (تومان)')], default='percent', max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='معتبر از تاریخ'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='معتبر تا تاریخ'),
        ),
    ]
