# Generated by Django 6.0 on 2026-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_coupon_options_coupon_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال (تومان)')),
                ('free_threshold', models.DecimalField(blank=True, decimal_places=0, help_text='خالی بگذارید تا ارسال رایگان همیشه غیرفعال باشد.', max_digits=12, null=True, verbose_name='ارسال رایگان از این مبلغ به بالا (تومان)')),
            ],
            options={
                'verbose_name': 'تنظیمات ارسال',
                'verbose_name_plural': 'تنظیمات ارسال',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال (تومان)'),
        ),
    ]
