# Generated by Django 6.0 on 2026-07-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_shippingsettings_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, choices=[('post', 'پست'), ('tipax', 'تیپاکس')], max_length=10, verbose_name='شرکت حمل'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد رهگیری'),
        ),
    ]
