# Generated by Django 6.0 on 2026-06-30 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به شکل ۰۹XXXXXXXXX باشد.', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به شکل ۰۹XXXXXXXXX باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
