# Generated by Django 6.0 on 2026-07-01 07:39

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_receiver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.common.validators.validate_image_file], verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'کاربری با این ایمیل قبلاً ثبت\u200cنام کرده است.'}, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'کاربری با این شماره موبایل قبلاً ثبت\u200cنام کرده است.'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید به شکل ۰۹XXXXXXXXX باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
