# Generated by Django 6.0 on 2026-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('successful', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20),
        ),
    ]
