# Generated by Django 6.0 on 2026-07-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
    ]
