# Generated by Django 6.0 on 2026-07-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_alter_order_created_at_and_more'),
        ('payments', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, help_text='کد پیگیری صادرشده توسط درگاه، در صورت وجود.', max_length=100, verbose_name='کد پیگیری تراکنش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='manual', help_text='مثلاً manual یا zarinpal', max_length=30, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('successful', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
