# Generated by Django 6.0 on 2026-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Remix Icon class, e.g. ri-paint-brush-line', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(choices=[('none', 'بدون برچسب'), ('bestseller', 'پرفروش'), ('new', 'جدید'), ('special_discount', 'تخفیف ویژه')], default='none', max_length=20),
        ),
    ]
