# Generated by Django 6.0 on 2026-06-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_color_product_brand_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'اسلایدر اصلی'), ('promo', 'بنر تبلیغاتی')], default='hero', max_length=10),
        ),
    ]
