# Generated by Django 6.0 on 2026-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_banner_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='توضیح کوتاه برای نتایج گوگل (حداکثر ۱۶۰ کاراکتر).', max_length=160, verbose_name='توضیحات سئو (meta description)'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='عنوانی که در نتایج گوگل و تب مرورگر نمایش داده می\u200cشود. خالی = نام محصول.', max_length=70, verbose_name='عنوان سئو (meta title)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='نمایش در بخش\u200cهای منتخب صفحه اصلی.'),
        ),
    ]
