# Generated by Django 6.0 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
