# Generated by Django 6.0 on 2026-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_banner_image_alter_banner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='color_products', to='catalog.color', verbose_name='رنگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='نشانی صفحه (اسلاگ)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='نشانی صفحه (اسلاگ)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True, verbose_name='نشانی صفحه (اسلاگ)'),
        ),
    ]
